---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present
  become: yes  

- name: adding bazel repo
  apt_repository:
    repo: deb https://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present
  become: yes
- name: Install bazel
  apt:
    name: bazel
    state: present
  become: yes
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes  
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes  

        