---
      - name: Cloning my-settings from git
        git:
            repo: https://github.com/patilvinay/my-settings.git
            dest: "{{ansible_env.HOME}}/my-settings"
            force: yes
             
      - name: Install zsh
        apt:
          name: zsh
          state: present
        become: yes
      - name: Cloning oh-my-zsh from  
        git:
            repo:  https://github.com/ohmyzsh/ohmyzsh.git
            dest: "{{ansible_env.HOME}}/my-settings/oh-my-zsh"
            force: yes
      - name: Cloning zsh-autosuggestion from git
        git:
            repo:  https://github.com/zsh-users/zsh-autosuggestions
            dest: "{{ansible_env.HOME}}/my-settings/oh-my-zsh/plugins/zsh-autosuggestions"
            force: yes  
      - name: Cloning zsh-syntax-hylighting from git
        git:
            repo:  https://github.com/zsh-users/zsh-syntax-highlighting.git
            dest: "{{ansible_env.HOME}}/my-settings/oh-my-zsh/plugins/zsh-syntax-highlighting"
            force: yes  
      - name: Cloning zsh-you-should-use from git
        git:
            repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
            dest: "{{ansible_env.HOME}}/my-settings/oh-my-zsh/plugins/you-should-use"
            force: yes  
      - name: Cloning powerlevel10k from git
        git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{{ansible_env.HOME}}/my-settings/powerlevel10k"
            force: yes
      - name: Setup .oh-my-zsh
        file:
          src: "{{ansible_env.HOME}}/my-settings/oh-my-zsh"
          dest: "{{ansible_env.HOME}}/.oh-my-zsh"
          state: link
      - name: Setup powerlevel10K
        file:
          src: "{{ansible_env.HOME}}/my-settings/powerlevel10k"
          dest: "{{ansible_env.HOME}}/.powerlevel10k"
          state: link
     
      - name: Setup zshrc
        file:
          src: "{{ansible_env.HOME}}/my-settings/conf/.zshrc"
          dest: "{{ansible_env.HOME}}/.zshrc"
          state: link
      - name: Setup  p10k.zsh
        file:
          src: "{{ansible_env.HOME}}/my-settings/conf/.p10k.zsh"
          dest: "{{ansible_env.HOME}}/.p10k.zsh"
          state: link
      - name: Change default shell to zsh 
        become: yes
        user:
           name: "{{ the_user }}"
           shell: /bin/zsh
