- hosts: localhost
  connection: local
  vars_files:
      - vars.yml
  gather_facts: no
  tasks:

  #  - name: Install doctl
  #    snap:
  #      name:
  #        - doctl
  #      state: present  
  #    become: yes  


   - name: Creating Digital Ocean Cluster  
     shell: doctl k8s cluster create  --size {{ do.size }} --count {{ do.count}} --region {{ do.region }} --tag {{ do.tag }} --update-kubeconfig {{ do.name }}  --version {{ do.version }}
     register: result
     #become: yes   
   - debug: 
       var:  result.stdout_lines

