- hosts: localhost
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"
  roles: 
    - zsh
    - tmux

  tasks:
    - name: Installing packages
      apt:
        pkg:
        - git
        - g++
        - make
        - curl
        - vim
        - software-properties-common
        - jq
      become: yes
