- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Installing k14s  
     shell: curl -L https://k14s.io/install.sh | bash
     register: result
     become: yes   
   - debug: 
       var:  result.stdout_lines
