- hosts: localhost
  connection: local
  gather_facts: no
  become: vagrant
  environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/kindconfig-new"
  roles:
    - role: ngx.kind
      vars:
       - kube_path: "{{ lookup('env','HOME') }}/.kube/"
       - kube_configfile: kindconfig-new   
       - path: /usr/local/istio/bin

 
