- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Installing gofish
     shell: curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
     register: result
     become: yes

  #  - name: gofish Init
  #    shell: gofish init
  #    register: result
  #    become: yes
  #  - debug:
  #      var:  result.stdout_lines

  #  - name: Installing draft
  #    shell: gofish install draft
  #    register: result
  #    become: yes

   - name: Installing yq
     shell: curl -L --output /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64
     register: result
     become: yes

   - name: Change file ownership, group and permissions
     file:
        path: /usr/local/bin/yq
        mode: u=xrw,g=xr,o=xr
     become: yes

   - name: Installing k14s
     shell: curl -L https://k14s.io/install.sh | bash
     register: result
     become: yes
     when: false
