
 do:
   size: s-2vcpu-4gb
   count: 3
   region: blr1
   tag: k8s
   version: 1.16.6-do.2
   name: k8s-090420


 kube:
   configfile: config
   #context:  do-{{ do.region }}-{{ do.name }}
   context:  kind-kind

 ngx:
    app_name: ms-business
    ns: ngx-ns
    chart: "~/d2/nbp-ms"
    context: "{{ kube.context }}"
    configfile: "{{ kube.configfile }}"
    chartclone: false
    domain: "api.ngxconnect.in"

 cert_manager:
   version: v0.14.1

